spring:
  application:
    name: product-service
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://postgres-db:5432/productdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true


server:
  port: 8081